// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRn-VbdpdnEIoBfxbOmBDLlRJm1pHNVCA',
    appId: '1:819736173231:web:7d49bea15aa634faf0125a',
    messagingSenderId: '819736173231',
    projectId: 'tuparking-43853',
    authDomain: 'tuparking-43853.firebaseapp.com',
    storageBucket: 'tuparking-43853.appspot.com',
    measurementId: 'G-YF6J5CDRLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbafkRx5320UKea31_WX_lL0x9xNoaJg',
    appId: '1:819736173231:android:91f5427a6678d9b2f0125a',
    messagingSenderId: '819736173231',
    projectId: 'tuparking-43853',
    storageBucket: 'tuparking-43853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8NQBBYZdsbiCr0ek73RUdvAaAKwzRDc',
    appId: '1:819736173231:ios:2f805b096e79bda9f0125a',
    messagingSenderId: '819736173231',
    projectId: 'tuparking-43853',
    storageBucket: 'tuparking-43853.appspot.com',
    iosBundleId: 'com.example.tuparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp8NQBBYZdsbiCr0ek73RUdvAaAKwzRDc',
    appId: '1:819736173231:ios:c71c34db118c7253f0125a',
    messagingSenderId: '819736173231',
    projectId: 'tuparking-43853',
    storageBucket: 'tuparking-43853.appspot.com',
    iosBundleId: 'com.example.tuparking.RunnerTests',
  );
}
